<a href="https://colab.research.google.com/github/jibook/git-remote/blob/master/17_class_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(88)
df = pd.DataFrame({'A':np.linspace(1,10,10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10,4), columns=list('BCDE'))], axis =1)

In [ ]:
df.iloc[3,3] = np.nan
df.iloc[0,2]  =np.nan

In [ ]:
print(df)

      A         B         C         D         E
0   1.0  0.106884       NaN  0.956563  0.068411
1   2.0  1.068514  0.997183 -0.931548  0.730430
2   3.0 -0.171214 -1.288691  1.061436 -0.040501
3   4.0 -0.903721 -1.554133       NaN  0.200526
4   5.0 -0.747329  1.068081 -0.277024  0.086557
5   6.0 -0.253221 -1.212041  0.277273  0.552219
6   7.0 -0.467743 -1.427493  0.885805  2.360634
7   8.0 -1.522006 -0.215945  0.190327  0.722256
8   9.0 -0.870716  0.101749  0.555358  0.962261
9  10.0  1.433499 -0.701818 -0.856952 -0.858158

In [ ]:
df.style.highlight_max()

In [ ]:
df.style.highlight_max(axis=1)

In [ ]:
df.style.highlight_min()

In [ ]:
df.style.highlight_null()

In [ ]:
df.style.highlight_null(null_color='green')

In [ ]:
df.style.set_na_rep('OutoScope').highlight_null(null_color='orange')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(na_rep=..)`
  """Entry point for launching an IPython kernel.

In [ ]:
df.style.background_gradient()

In [ ]:
df.style.set_properties(**{'border':'1.3px solid green', 'color':'magenta'})

In [ ]:
df.style.bar()

In [ ]:
df.style.bar(color='green ')

In [ ]:
df.style.set_precision(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  """Entry point for launching an IPython kernel.

In [ ]:
df.style.set_caption("This is DataFrame styling demo").set_precision(2).background_gradient()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: this method is deprecated in favour of `Styler.format(precision=..)`
  """Entry point for launching an IPython kernel.

In [ ]:
df.style.hide_index()

In [ ]:
df.style.hide_columns('B')

In [ ]:
df.style.format("{:.3%}")

In [ ]:
df.style.format("{:.3%}", na_rep = "&&")

In [ ]:
# p30부터